import { concept } from "./build";

/**
 * Data modelling and dbt concept questions.
 *
 * Weighted by what the research measured rather than by what is most written
 * about. Across 67 modelling problems collected from real loops, surrogate and
 * natural keys appear in 100%, cardinality and junction tables in 99%, grain in
 * 93%, fact and dimension tables in 85%, star versus snowflake in 79% and
 * metric additivity in 64% — while SCD Type 2, which dominates the blog posts,
 * appears in 24%.
 *
 * The dbt half follows dbt Labs' own certification outline, which is the only
 * authoritative statement of what dbt knowledge is actually tested, plus the
 * three areas no published question bank covers at all: unit tests, model
 * contracts and the semantic layer.
 */
export const MODELLING_CONCEPTS = [
  // ---- Fundamentals ------------------------------------------------------
  concept("dimensional-modelling", "easy", "What is data modelling, and why does it matter?",
    "What is data modelling in analytics, and why does it matter?"),
  concept("dimensional-modelling", "easy", "What is grain, and why start there?",
    "What is the grain of a fact table, and why does everyone say to establish it before anything else?"),
  concept("dimensional-modelling", "easy", "Fact tables and dimension tables",
    "What is the difference between a fact table and a dimension table? Give me a test you'd use when something is ambiguous."),
  concept("dimensional-modelling", "easy", "Conceptual, logical and physical models",
    "Explain the difference between a conceptual, a logical and a physical data model. Who is each one for?"),
  concept("dimensional-modelling", "easy", "OLTP versus OLAP",
    "What is the difference between an OLTP and an OLAP system, and how does that change how you model for each?"),
  concept("dimensional-modelling", "medium", "Star schema or snowflake schema?",
    "What is the difference between a star schema and a snowflake schema, and which would you choose for a new warehouse? Say what would change your mind."),
  concept("dimensional-modelling", "medium", "The types of fact table",
    "Walk me through the main types of fact table — transaction, periodic snapshot and accumulating snapshot — and when you'd reach for each."),
  concept("dimensional-modelling", "hard", "Which fact table type is hardest to maintain?",
    "Of the three fact table types, which is the most painful to maintain in a pipeline, and why?"),
  concept("dimensional-modelling", "medium", "Additive, semi-additive and non-additive measures",
    "What are additive, semi-additive and non-additive measures? What goes wrong in a BI tool if you don't handle the distinction?"),
  concept("dimensional-modelling", "medium", "What is a factless fact table?",
    "What is a factless fact table, and what kind of question does it answer that a normal fact table can't?"),
  concept("dimensional-modelling", "medium", "Products that were NOT sold",
    "The business wants to know which products were not sold in each store last month. How do you model that?"),

  // ---- Keys and relationships -------------------------------------------
  concept("dimensional-modelling", "easy", "Surrogate keys or natural keys?",
    "What is a surrogate key, and why do warehouses default to them instead of the key the source already gives you?"),
  concept("dimensional-modelling", "hard", "Hash or sequence for a surrogate key?",
    "In a distributed loader, would you generate surrogate keys by hashing or from a sequence? What are the trade-offs?"),
  concept("dimensional-modelling", "medium", "Degenerate dimensions",
    "What is a degenerate dimension? Where does an order number live, and why isn't it its own table?"),
  concept("dimensional-modelling", "medium", "Junk dimensions",
    "What is a junk dimension, and when does one become a bad idea?"),
  concept("dimensional-modelling", "medium", "Role-playing dimensions",
    "What is a role-playing dimension? You have one date dimension and three dates on a fact — order date, ship date, delivery date. How do you handle it?"),
  concept("dimensional-modelling", "medium", "Bridge tables",
    "What is a bridge table, and what problem does it solve that a normal join can't?"),
  concept("dimensional-modelling", "hard", "Revenue through a bridge exceeds real revenue",
    "You sum revenue through a bridge table and the total comes out higher than actual revenue. What caused it, and is it necessarily wrong?"),
  concept("dimensional-modelling", "medium", "What makes a dimension conformed?",
    "What makes a dimension conformed, and why is it worth the trouble?"),
  concept("dimensional-modelling", "hard", "Two teams disagree on what a customer is",
    "Sales and finance genuinely disagree about what counts as a customer. What do you actually build?"),
  concept("dimensional-modelling", "hard", "Modelling a hierarchy",
    "How would you model a hierarchy — an org chart, or a category tree — so that analysts can roll up at any level?"),
  concept("dimensional-modelling", "hard", "Rollup as of last March",
    "Your org chart is a hierarchy and it's also Type 2. Someone asks for a rollup as of last March. What does that require?"),

  // ---- History -----------------------------------------------------------
  concept("dimensional-modelling", "medium", "SCD Types 1, 2 and 3",
    "Explain slowly changing dimension Types 1, 2 and 3, and tell me how you choose between them."),
  concept("dimensional-modelling", "hard", "Implementing SCD Type 2",
    "Walk me through implementing a Type 2 dimension end to end — the columns, the keys, and how a fact joins to the right version."),
  concept("dimensional-modelling", "hard", "Which attributes deserve Type 2?",
    "In a customer dimension, which attributes would you version with Type 2 and which would you leave as Type 1? Use a real example."),
  concept("dimensional-modelling", "hard", "Two changes between loads",
    "A source row changed twice between your daily snapshot loads. What does your dimension miss, and does it matter?"),
  concept("dimensional-modelling", "hard", "Daily snapshots instead of Type 2",
    "When is taking a full daily snapshot of a dimension the better choice than implementing Type 2?"),
  concept("dimensional-modelling", "hard", "Late-arriving dimensions",
    "A fact arrives but the dimension row it points at hasn't loaded yet. What do you do with it?"),
  concept("dimensional-modelling", "hard", "The dimension arrives with a correction to history",
    "Your Type 2 dimension is loaded, and then the source sends a correction to a value from six months ago. Now what?"),
  concept("dimensional-modelling", "medium", "Late-arriving facts",
    "Your daily pipeline processes orders by processing date. An order from ten days ago arrives today. What happens?"),

  // ---- Normalisation and architecture -----------------------------------
  concept("dimensional-modelling", "easy", "What is normalisation?",
    "What is normalisation, and can you walk me through first, second and third normal form?"),
  concept("dimensional-modelling", "medium", "When do you denormalise on purpose?",
    "When would you deliberately denormalise, and what are you accepting when you do?"),
  concept("dimensional-modelling", "medium", "3NF or star schema in the warehouse?",
    "When would you choose a normalised 3NF model over a denormalised star schema in an analytics warehouse?"),
  concept("dimensional-modelling", "hard", "Star schema or One Big Table?",
    "Star schema versus One Big Table — make the case for each, and tell me which query shapes get worse on OBT rather than better."),
  concept("dimensional-modelling", "hard", "Kimball, Inmon or Data Vault?",
    "You're at an organisation with eight engineers, forty sources and heavy compliance requirements. Which modelling methodology goes where, concretely?"),
  concept("dimensional-modelling", "medium", "What is medallion architecture?",
    "What is medallion architecture, and what does each layer actually promise?"),
  concept("dimensional-modelling", "hard", "Snowflake the product, snowflake the schema",
    "Your team is building on Snowflake, and a junior engineer proposes a snowflake schema to save storage. Do you agree?"),
  concept("dimensional-modelling", "hard", "Partitioning a multi-terabyte fact table",
    "How do you choose a partition column for a multi-terabyte fact table, and what happens when queries filter on something else?"),
  concept("dimensional-modelling", "hard", "Schema evolution as a contract problem",
    "Treat schema evolution as a contract problem. Who is allowed to change what, and how does a producer rename a column with zero consumer downtime?"),
  concept("dimensional-modelling", "medium", "Preventing double counting",
    "How do you stop an analytical model from double counting? Name the mechanisms you'd put in place, not just the symptom."),
  concept("dimensional-modelling", "medium", "Validating a model after a change",
    "You've changed a data model that's already in production. How do you validate it before anyone reports a wrong number?"),
  concept("dimensional-modelling", "medium", "Is it a fact or a dimension attribute?",
    "You have a column called customer_lifetime_revenue. Is that a fact or a dimension attribute? Defend it."),

  // ---- dbt: fundamentals -------------------------------------------------
  concept("dbt-modelling", "easy", "ref() versus source()",
    "In dbt, what is the difference between ref() and source(), and what breaks if you hardcode a table name instead?"),
  concept("dbt-modelling", "medium", "The four materializations",
    "Explain dbt's materializations — view, table, incremental and ephemeral — and give me a use case for each."),
  concept("dbt-modelling", "medium", "Views on views on views",
    "A project has staging views built on staging views built on staging views. Nothing is materialised. What's wrong with that?"),
  concept("dbt-modelling", "medium", "When does a model become incremental?",
    "When would you make a dbt model incremental, and what do you give up by doing it?"),
  concept("dbt-modelling", "hard", "Designing a reliable unique_key",
    "How do you choose a unique_key for an incremental model, and what happens if the key isn't actually unique at the model's grain?"),
  concept("dbt-modelling", "medium", "Forgetting the unique_key",
    "What happens if you forget to set a unique_key on a merge-strategy incremental model?"),
  concept("dbt-modelling", "medium", "Where does is_incremental() go?",
    "What is the is_incremental() macro, where exactly does it belong in a model, and what is it guarding against?"),
  concept("dbt-modelling", "hard", "The four incremental strategies",
    "What are dbt's incremental strategies — append, merge, delete+insert, insert_overwrite — and when do you pick each?"),
  concept("dbt-modelling", "hard", "insert_overwrite versus merge",
    "How does insert_overwrite differ from merge, and why does that difference matter particularly on BigQuery?"),
  concept("dbt-modelling", "hard", "Late-arriving data in an incremental model",
    "How do you handle late-arriving data in an incremental dbt model? What does a naive watermark filter miss?"),
  concept("dbt-modelling", "medium", "The on_schema_change config",
    "What does the on_schema_change config do on an incremental model, and which setting would you choose?"),
  concept("dbt-modelling", "medium", "An incremental model is silently full-refreshing",
    "An incremental model has started taking an hour instead of a minute, and nobody changed the schedule. Where do you look?"),

  // ---- dbt: snapshots, tests, docs ---------------------------------------
  concept("dbt-modelling", "medium", "What are dbt snapshots?",
    "What are snapshots in dbt, and how do they differ from an incremental model?"),
  concept("dbt-modelling", "medium", "Timestamp or check strategy?",
    "Compare the timestamp and check strategies for a dbt snapshot. When are you forced into check?"),
  concept("dbt-modelling", "medium", "dbt_valid_from and dbt_valid_to",
    "Explain what dbt_valid_from and dbt_valid_to give you in a snapshot, and how you'd query it for a point in time."),
  concept("dbt-modelling", "hard", "What a snapshot can never capture",
    "What changes can a dbt snapshot never capture, however it's configured? What does that mean for how often you run it?"),
  concept("dbt-modelling", "medium", "Generic tests and singular tests",
    "What is the difference between a generic test and a singular test in dbt, and when would you write each?"),
  concept("dbt-modelling", "medium", "Writing a custom generic test",
    "How do you turn a one-off singular test into a reusable custom generic test?"),
  concept("dbt-modelling", "medium", "What does severity do?",
    "What does the severity config do on a dbt test, and why does it matter for whether people pay attention to test output?"),
  concept("dbt-modelling", "medium", "Your testing strategy for a production project",
    "Describe your testing strategy for a production dbt project. What gets tested where, and what do you deliberately not test?"),
  concept("dbt-modelling", "medium", "Testing sources",
    "What are sources in dbt, and how do you test them? What does source freshness actually protect you from?"),
  concept("dbt-modelling", "medium", "Documentation that people read",
    "How do you approach documentation in a dbt project so it's maintained rather than written once and abandoned?"),
  concept("dbt-modelling", "medium", "What are exposures for?",
    "What is a dbt exposure, and what does declaring one buy you?"),

  // ---- dbt: macros, structure, state -------------------------------------
  concept("dbt-modelling", "medium", "What are macros, and when should you use one?",
    "What are macros in dbt, and when should you reach for one rather than repeating yourself?"),
  concept("dbt-modelling", "hard", "When a macro is the wrong answer",
    "When does a dbt macro make a project worse? How do you debug logic that lives inside one?"),
  concept("dbt-modelling", "medium", "Structuring a project",
    "Describe how you'd structure a dbt project. What belongs in staging, intermediate and marts, and why must staging stay thin?"),
  concept("dbt-modelling", "medium", "Packages and external dependencies",
    "How do you manage packages and external dependencies in a dbt project, and what's the risk of pinning or not pinning versions?"),
  concept("dbt-modelling", "hard", "What is the manifest, and why care?",
    "What is manifest.json, and why is it the thing that makes slim CI possible?"),
  concept("dbt-modelling", "hard", "state:modified and deferral",
    "What does state:modified selection do, and what is deferral? Why do you need both for CI to be fast?"),
  concept("dbt-modelling", "hard", "Setting up CI for dbt",
    "How would you implement CI for a dbt project? Walk me through what runs on a pull request and what doesn't."),
  concept("dbt-modelling", "hard", "Relation does not exist",
    "A dbt model fails with 'relation does not exist'. Walk me through debugging it, and tell me how you'd know whether it's a dbt problem or a SQL problem."),
  concept("dbt-modelling", "hard", "A model is taking too long",
    "A dbt model has become the slowest thing in the run. How would you debug and optimise it?"),
  concept("dbt-modelling", "medium", "dbt Core or dbt Cloud?",
    "What is the difference between dbt Core and dbt Cloud, and when would you choose each?"),

  // ---- dbt: the uncovered ground -----------------------------------------
  concept("dbt-modelling", "hard", "What are dbt unit tests for?",
    "What are dbt unit tests, and how do they differ from the data tests you'd put on a model?"),
  concept("dbt-modelling", "hard", "When is a unit test worth writing?",
    "Which dbt models justify a unit test, and which don't? Give me the logic you'd apply."),
  concept("dbt-modelling", "hard", "Model contracts",
    "What is a dbt model contract, and what problem does enforcing one at build time solve?"),
  concept("dbt-modelling", "hard", "Model versions",
    "What are dbt model versions for, and how do they change how you ship a breaking schema change?"),
  concept("dbt-modelling", "hard", "Access modifiers and groups",
    "What do dbt's access modifiers and groups do, and what goes wrong in a large project without them?"),
  concept("dbt-modelling", "hard", "What is the semantic layer for?",
    "What problem does a semantic layer like MetricFlow solve that a well-built marts layer doesn't?"),
  concept("dbt-modelling", "hard", "Defining a metric once",
    "Walk me through defining a metric in MetricFlow. What does defining it once actually prevent?"),
  concept("dbt-modelling", "hard", "Cross-project refs and dbt Mesh",
    "What is a cross-project ref, and when would you split a monolithic dbt project into several?"),
];
