import { concept } from "./build";

/**
 * Pipeline, ETL and orchestration concept questions.
 *
 * Ordered by measured frequency across 144 pipeline design problems from real
 * loops: idempotency appears in 95% of them, data quality checks 89%,
 * monitoring 86%, partitioning 84%, retries 76%, deduplication 74%,
 * full-versus-incremental 72%, DAG orchestration 65%, late-arriving data 62%,
 * batch versus streaming 61%, schema evolution 53%.
 *
 * This is also the round candidates fail most — a 28% pass rate against 91%
 * for SQL — and at staff level it is most of the loop.
 */
export const PIPELINE_CONCEPTS = [
  // ---- Idempotency and correctness ---------------------------------------
  concept("pipeline-etl", "medium", "What does idempotency mean, concretely?",
    "What does idempotency mean in a pipeline? Don't define it — tell me what you'd actually change in a load to get it."),
  concept("pipeline-etl", "hard", "Making a SQL pipeline idempotent",
    "How do you make a SQL data pipeline idempotent? Walk me through the specific write pattern."),
  concept("pipeline-etl", "medium", "Why reruns duplicate",
    "A job failed halfway, someone reran it, and now there are duplicate rows. Explain exactly how that happened and how you'd prevent it."),
  concept("pipeline-etl", "hard", "At-least-once, at-most-once, exactly-once",
    "Explain at-least-once, at-most-once and exactly-once delivery. Which do you actually get, and which do you build for?"),
  concept("pipeline-etl", "hard", "Is exactly-once real?",
    "Is exactly-once processing real, or is it marketing? Be specific about what is genuinely guaranteed and where."),
  concept("pipeline-etl", "hard", "Exactly-once into the OLAP store",
    "Product wants exactly-once delivery into the analytics warehouse. What does that actually require, end to end?"),
  concept("pipeline-etl", "hard", "A sink with no idempotency support",
    "Your pipeline's destination is an external API with no idempotency key and no deduplication. How do you make the load safe?"),
  concept("pipeline-etl", "medium", "Deduplicating a batch",
    "Your source sends the same record more than once. Where in the pipeline do you deduplicate, and what do you key on?"),

  // ---- Incremental loading -----------------------------------------------
  concept("pipeline-etl", "easy", "ETL or ELT?",
    "What is the difference between ETL and ELT, and what changed to make ELT the default?"),
  concept("pipeline-etl", "easy", "Full load or incremental load?",
    "What is the difference between a full load and an incremental load, and how do you decide when to switch?"),
  concept("pipeline-etl", "hard", "What a watermark misses",
    "You're loading incrementally on an updated_at watermark. Name two classes of change that filter will never see."),
  concept("pipeline-etl", "hard", "Handling deletes",
    "Your source hard-deletes rows. An updated_at watermark cannot see that. What are your options, ranked?"),
  concept("pipeline-etl", "hard", "No updated_at and no CDC",
    "The source has no updated_at column and you cannot install CDC on it. Rank your remaining options by how ugly they are."),
  concept("pipeline-etl", "medium", "Rows that change during the extract",
    "Rows are being updated while your extract is running. What does that do to your watermark, and how do you handle it?"),
  concept("pipeline-etl", "medium", "What is change data capture?",
    "What is change data capture, and why would you use it instead of polling the source?"),
  concept("pipeline-etl", "hard", "CDC sources and their trade-offs",
    "Compare the common CDC mechanisms — reading the write-ahead log, triggers, and query-based polling. What does each cost you?"),
  concept("pipeline-etl", "hard", "Ordering in CDC",
    "Why is preserving order hard in a CDC pipeline, and what goes wrong downstream when you lose it?"),
  concept("pipeline-etl", "hard", "CDC versus dual writes",
    "Why is writing to both your database and your warehouse from the application a trap? What does CDC do differently?"),
  concept("pipeline-etl", "hard", "The outbox pattern",
    "What is the outbox pattern, and which specific failure does it prevent?"),
  concept("pipeline-etl", "medium", "Monitoring CDC lag",
    "How do you monitor CDC lag, and what are the places lag can come from?"),

  // ---- Backfills ----------------------------------------------------------
  concept("pipeline-etl", "hard", "Why interviewers keep asking about backfills",
    "Why do interviewers keep asking about backfills? What does the answer reveal about how someone builds pipelines?"),
  concept("pipeline-etl", "hard", "A backfill that won't take production down",
    "Design a backfill of two years of data that won't take production down. What are the constraints you'd set?"),
  concept("pipeline-etl", "hard", "Mid-backfill, the new logic is also wrong",
    "You're halfway through a large backfill and you discover the new logic is also wrong. What does a well-designed backfill let you do at that point?"),
  concept("pipeline-etl", "hard", "Replaying a corrupted layer",
    "A bug corrupted your silver layer for the last thirty days. Walk me through the actual replay, including what happens to the consumers."),
  concept("pipeline-etl", "medium", "Oldest-first or newest-first?",
    "When backfilling a long date range, do you process oldest-first or newest-first? Justify it."),

  // ---- Late and out-of-order data ----------------------------------------
  concept("pipeline-etl", "hard", "Event time versus processing time",
    "Explain event time versus processing time. Which do you partition on, and why does the answer matter?"),
  concept("pipeline-etl", "hard", "What does a watermark bound?",
    "Where does a watermark fit in a streaming pipeline, and what exactly does it bound?"),
  concept("pipeline-etl", "hard", "Your watermark is too aggressive",
    "Your watermark is too aggressive and 2% of conversions are landing late and being dropped. Who notices, and what's the correction path?"),
  concept("pipeline-etl", "medium", "The lookback window",
    "What is a lookback window in an incremental load, and how do you choose its size?"),

  // ---- Quality gates and failure handling --------------------------------
  concept("pipeline-etl", "medium", "What is a dead letter queue for?",
    "What is a dead-letter queue for, and what goes wrong in a pipeline that doesn't have one?"),
  concept("pipeline-etl", "hard", "Where do bad rows go?",
    "Your load hits a malformed record. Walk me through exactly what happens to that row, and what makes the whole run stop instead."),
  concept("pipeline-etl", "hard", "Block or ship flagged data?",
    "Should a failed quality check block the pipeline or let flagged data through? Who decides that per table, and where is the decision written down?"),
  concept("pipeline-etl", "hard", "Dead letter rate jumps but the pipeline is green",
    "Your dead-letter rate went from 0.1% to 4% overnight and every pipeline is showing green. What does your system do about that?"),
  concept("pipeline-etl", "medium", "Retries and backoff",
    "What's your retry strategy for a flaky upstream API, and which failures should you not retry at all?"),
  concept("pipeline-etl", "hard", "Reliability patterns",
    "What are the main reliability patterns you'd build into a pipeline that runs unattended every night?"),
  concept("pipeline-etl", "medium", "Keeping a raw layer trustworthy",
    "What does it mean to keep a raw layer trustworthy, and what are you not allowed to do to it?"),

  // ---- Schema evolution ---------------------------------------------------
  concept("pipeline-etl", "hard", "Handling schema evolution",
    "How do you handle schema evolution in an ingestion pipeline? Distinguish the changes that are safe from the ones that aren't."),
  concept("pipeline-etl", "hard", "CDC delivers a schema change mid-day",
    "Your CDC stream delivers a schema change event at two in the afternoon. What happens downstream in your design?"),
  concept("pipeline-etl", "hard", "What are data contracts?",
    "What is a data contract, and what has to be true organisationally for one to actually work?"),

  // ---- Batch, streaming, architecture ------------------------------------
  concept("pipeline-etl", "medium", "Batch or streaming?",
    "How do you decide between batch and streaming? Give me the question you'd ask the business, not the technical comparison."),
  concept("pipeline-etl", "hard", "Lambda or Kappa?",
    "Explain lambda and kappa architecture, and what each one picks up and gives away."),
  concept("pipeline-etl", "hard", "Streaming for a team that doesn't stream",
    "A stakeholder asks for real-time data. How do you find out whether they actually need it?"),
  concept("pipeline-etl", "medium", "Raw, silver and gold",
    "How do you decide what belongs in raw, silver and gold? What's the rule for whether a transformation moves up a layer?"),
  concept("pipeline-etl", "hard", "A platform for multiple teams",
    "How would you design a data platform that several teams build on without breaking each other?"),
  concept("pipeline-etl", "hard", "Managing cost while meeting an SLA",
    "How do you manage warehouse cost while still meeting a delivery SLA? What are you willing to trade?"),

  // ---- Monitoring ---------------------------------------------------------
  concept("pipeline-etl", "medium", "What do you alert on?",
    "How do you monitor a pipeline, and what specifically do you alert on? What do you deliberately not alert on?"),
  concept("pipeline-etl", "hard", "Completeness signals versus cron",
    "What's the difference between triggering a downstream job on a schedule and triggering it on a completeness signal? Why does it matter?"),
  concept("pipeline-etl", "hard", "A pipeline that silently stopped",
    "A pipeline stopped running three days ago and never failed — it just never started. Why didn't anything catch it?"),
];

export const ORCHESTRATION_CONCEPTS = [
  concept("orchestration", "easy", "What does a DAG give you over cron?",
    "What is orchestration, and what does a DAG give you that a set of cron jobs doesn't?"),
  concept("orchestration", "easy", "What problems does Airflow solve?",
    "What problems does a scheduler like Airflow actually solve? What was painful before it?"),
  concept("orchestration", "medium", "Airflow's architecture",
    "Walk me through Airflow's components — scheduler, executor, metadata database, workers — and how a task actually gets run."),
  concept("orchestration", "medium", "Choosing an executor",
    "Compare LocalExecutor, CeleryExecutor and KubernetesExecutor. When would you choose each?"),
  concept("orchestration", "hard", "The scheduler parsing loop",
    "Explain Airflow's scheduler parsing loop, and why it matters that DAG files execute quickly."),
  concept("orchestration", "hard", "Top-level code in a DAG file",
    "Why is putting a database call or an API request at the top level of a DAG file a serious mistake?"),
  concept("orchestration", "hard", "execution_date versus now",
    "What is the difference between a run's logical date and the wall-clock time it actually runs? Why does this confuse so many people?"),
  concept("orchestration", "medium", "Which window does a run cover?",
    "A daily job runs at 02:00. Which day's data is it processing, and how would you make that unambiguous in the code?"),
  concept("orchestration", "medium", "Yesterday failed, today is queued",
    "Yesterday's run failed and today's is queued behind it. What happens, and how do you want it to behave?"),
  concept("orchestration", "hard", "Catchup versus backfill",
    "What's the difference between catchup and backfill in Airflow, and when has catchup bitten you?"),
  concept("orchestration", "medium", "Idempotent tasks",
    "How do you make an Airflow task idempotent, and why does the scheduler's retry behaviour make it non-negotiable?"),
  concept("orchestration", "medium", "Retries and retry_delay",
    "How do you configure retries in a scheduler, and what makes a retry dangerous rather than helpful?"),
  concept("orchestration", "medium", "Cross-DAG dependencies",
    "How do you handle a dependency between two separate DAGs? Compare the approaches."),
  concept("orchestration", "medium", "Sensors and their cost",
    "What is a sensor, and what's the problem with having a lot of them?"),
  concept("orchestration", "medium", "What are pools for?",
    "What are Airflow pools, and how would you use them to stop one job starving everything else?"),
  concept("orchestration", "medium", "XComs and their limits",
    "What are XComs for, and what should never go through one?"),
  concept("orchestration", "hard", "Dynamic task generation",
    "Explain dynamic task generation in a DAG. What does it buy you, and what does it cost?"),
  concept("orchestration", "hard", "Testing a DAG before it ships",
    "How do you test a DAG before deploying it? What can you actually assert?"),
  concept("orchestration", "hard", "Clearing versus marking success",
    "What's the difference between clearing a task and marking it successful, and when have you needed each?"),
  concept("orchestration", "hard", "Structuring DAGs across a team",
    "How do you structure DAGs across a team — one big DAG, one per source, one per domain? Defend your choice."),
  concept("orchestration", "hard", "Who owns which pipeline?",
    "You own five pipelines, two of which report metrics to investors. How do you set up ownership and an on-call rotation that's actually fair?"),
  concept("orchestration", "hard", "What belongs in a runbook?",
    "What goes in a runbook for a business-critical pipeline? Write it for the person woken at 3am who didn't build it."),
  concept("orchestration", "hard", "A task fails at 2am",
    "A task fails at 2am and pages you. Walk me through your first fifteen minutes."),
  concept("orchestration", "medium", "Alert fatigue",
    "Your team has stopped reading pipeline alerts. How did that happen, and how do you fix it?"),
];
