import { concept } from "./build";

/**
 * Python, performance, Spark and warehouse concept questions.
 *
 * The Python set deliberately avoids algorithm trivia. Every source in the
 * research says the same thing about this round — "DE Python is not LeetCode,
 * it is data manipulation" — and one rubric note is worth designing to:
 * reaching for pandas in a vanilla Python round is a common rejection signal.
 *
 * The performance set is written as diagnosis, because that is how it is
 * asked. A practitioner put it bluntly: a slow query is analysed with a query
 * plan or the Spark UI, and you do not need a complexity class to read either.
 */
export const PYTHON_CONCEPTS = [
  concept("python-data", "easy", "Generators versus lists",
    "When do you use a generator instead of a list, and when does lazy evaluation actually matter in a pipeline?"),
  concept("python-data", "medium", "A 100GB CSV on a 16GB machine",
    "You need to clean a 100GB CSV and it won't fit in memory, so pandas.read_csv is out. How do you do it?"),
  concept("python-data", "medium", "Dicts as GROUP BY",
    "How do you group and aggregate records in plain Python without pandas, and why might an interviewer insist on that?"),
  concept("python-data", "medium", "When not to reach for pandas",
    "When do you reach for pandas in a data engineering interview, and when is doing so a mistake?"),
  concept("python-data", "easy", "Counter and defaultdict",
    "What are Counter and defaultdict for, and what do they replace?"),
  concept("python-data", "easy", "The mutable default argument",
    "What goes wrong with a mutable default argument in Python, and why does it surprise people?"),
  concept("python-data", "easy", "Shallow copy and deep copy",
    "What's the difference between a shallow and a deep copy, and when has that distinction caused you a bug?"),
  concept("python-data", "medium", "Mutability and why it matters in a pipeline",
    "What does mutability mean in Python, and why does a function that mutates its input behave differently on a retry?"),
  concept("python-data", "medium", "Does the GIL matter here?",
    "What is the GIL, and does it actually matter for data engineering work?"),
  concept("python-data", "medium", "Threading, multiprocessing or asyncio?",
    "Place threading, multiprocessing and asyncio correctly. Which one do you use to fetch ten thousand URLs?"),
  concept("python-data", "medium", "Retries with backoff and jitter",
    "How would you design a retry decorator with exponential backoff, and why does it need jitter?"),
  concept("python-data", "medium", "Context managers in a pipeline",
    "Where do context managers earn their place in pipeline code?"),
  concept("python-data", "hard", "Error handling for a ten-million-row ETL",
    "Design the error handling for a nightly ETL over ten million rows. What fails the run, and what doesn't?"),
  concept("python-data", "medium", "Logging that's worth having",
    "What logging practices matter for a data pipeline? What do you want in the log at 3am?"),
  concept("python-data", "medium", "Reading and writing Parquet efficiently",
    "How do you read and write Parquet efficiently from Python, and what does the format give you over CSV?"),
  concept("python-data", "medium", "Structuring a Python pipeline project",
    "How would you structure a Python project for data pipelines so that someone else can test and run it?"),
  concept("python-data", "medium", "Reproducible environments",
    "How do you manage dependencies so a pipeline that runs today still runs in six months?"),
  concept("python-data", "hard", "Testing a transformation",
    "How do you test a data transformation in Python? What do you use for fixtures?"),
  concept("python-data", "hard", "Profiling slow Python",
    "A Python job is slower than it should be. How do you find out where the time is going?"),
  concept("python-data", "hard", "Vectorisation",
    "What is vectorisation in NumPy, and why is it faster than a Python loop?"),
  concept("python-data", "hard", "Iterating DataFrame rows",
    "Why is iterating over DataFrame rows slow, and what do you do instead?"),
  concept("python-data", "hard", "A groupby that blows past memory",
    "A pandas groupby has run out of memory. Walk me through your options in order."),
  concept("python-data", "hard", "What is a point-in-time join?",
    "What is a point-in-time join, and why does machine learning care about it so much?"),
];

export const PERFORMANCE_CONCEPTS = [
  // ---- Query and warehouse ------------------------------------------------
  concept("performance", "medium", "Why columnar storage is faster here",
    "What are the advantages of a columnar data store for analytics, and what are the disadvantages?",
    "row-vs-columnar"),
  concept("performance", "medium", "What is partition pruning?",
    "What is partition pruning, and what are the common ways a query accidentally defeats it?",
    "partition-vs-cluster"),
  concept("performance", "medium", "Partitioning versus clustering",
    "What's the difference between partitioning and clustering, and how do you choose columns for each?",
    "partition-vs-cluster"),
  concept("performance", "hard", "Choosing a partition column",
    "How do you choose a partition column for a large fact table, and what do you do when queries filter on something else entirely?",
    "partition-vs-cluster"),
  concept("performance", "medium", "Predicate pushdown",
    "What is predicate pushdown, and what stops it from happening?"),
  concept("performance", "medium", "The small files problem",
    "What is the small files problem, why does it hurt, and how do you fix it?",
    "small-files"),
  concept("performance", "medium", "Parquet over CSV",
    "Why Parquet rather than CSV for an analytical workload? Be specific about what you gain.",
    "row-vs-columnar"),
  concept("performance", "hard", "Parquet, ORC, Avro, Iceberg, Delta",
    "Compare Parquet, Avro and the table formats like Iceberg and Delta. What layer does each operate at?"),
  concept("performance", "medium", "When does an index help?",
    "When does adding an index help, and what does it cost you on a write-heavy table?"),
  concept("performance", "hard", "Indexes in an analytical warehouse",
    "Why don't columnar warehouses use indexes the way OLTP databases do? What do they use instead?"),
  concept("performance", "hard", "Materialised views",
    "When is a materialised view the right answer, and when is it hiding a problem you should have fixed?"),
  concept("performance", "hard", "Diagnosing a cost spike",
    "Your warehouse bill doubled with no deploy. How do you find out where the money went?"),
  concept("performance", "hard", "Cost per query as a design constraint",
    "On an engine billed by bytes scanned, how does that change the way you model and write queries?"),
  concept("performance", "medium", "Approximate counts",
    "When is an approximate distinct count good enough, and what are you trading?"),

  // ---- Spark --------------------------------------------------------------
  concept("performance", "medium", "What actually happens when you run a Spark job",
    "Walk me through Spark's execution model — jobs, stages, tasks — and what causes a stage boundary."),
  concept("performance", "medium", "Narrow and wide transformations",
    "What's the difference between a narrow and a wide transformation, and why does it matter for performance?",
    "broadcast-vs-shuffle"),
  concept("performance", "medium", "Why is the shuffle expensive?",
    "What is a shuffle in Spark, and why is it the thing you design around?",
    "broadcast-vs-shuffle"),
  concept("performance", "medium", "groupByKey versus reduceByKey",
    "Why does groupByKey run out of memory where reduceByKey survives?",
    "broadcast-vs-shuffle"),
  concept("performance", "hard", "Diagnosing data skew",
    "Two tasks out of two hundred are taking hours. What's happening, and why won't adding executors help?",
    "skew"),
  concept("performance", "hard", "Salting a hot key",
    "Explain salting as a fix for skew. What does it cost, and when would you not do it?",
    "skew"),
  concept("performance", "medium", "When to broadcast a join",
    "When should you broadcast one side of a join, and what happens if the broadcast side is too big?",
    "broadcast-vs-shuffle"),
  concept("performance", "hard", "Adaptive query execution",
    "What does adaptive query execution do for you, and what problems does it solve without you writing anything?"),
  concept("performance", "hard", "Caching in Spark",
    "When does caching a DataFrame help, and when does it make a job worse?"),
  concept("performance", "hard", "Sizing executors",
    "How do you size Spark executors? What goes wrong with very large ones, and with very small ones?"),
  concept("performance", "hard", "Reading the Spark UI",
    "You've been paged about a slow Spark job. What do you open first, and what are you looking for?",
    "skew"),
  concept("performance", "hard", "The Catalyst optimizer",
    "What does the Catalyst optimizer do, and how would you check whether it's done what you expected?"),
  concept("performance", "hard", "Bucketing",
    "What is bucketing, and when does it pay for itself?"),
  concept("performance", "hard", "Is a LeetCode-for-Spark a good idea?",
    "Someone proposes building a coding-practice site for Spark. Why might that be the wrong way to get better at Spark?"),

  // ---- Warehouse specifics ------------------------------------------------
  concept("performance", "hard", "Snowflake micro-partitions",
    "How does Snowflake's micro-partitioning work, and what does clustering actually change?",
    "partition-vs-cluster"),
  concept("performance", "hard", "Sizing a Snowflake warehouse",
    "How do you decide what size warehouse to run a workload on? Is a bigger warehouse always more expensive?"),
  concept("performance", "medium", "Zero-copy clone and time travel",
    "What are zero-copy cloning and time travel useful for in day-to-day engineering?"),
  concept("performance", "hard", "BigQuery cost control",
    "On BigQuery, how do you keep a dashboard from costing a fortune? Name the specific levers."),
  concept("performance", "hard", "Redshift distribution and sort keys",
    "What are distribution keys and sort keys in Redshift, and what happens when you choose them badly?"),
  concept("performance", "hard", "The medallion layers on a lakehouse",
    "On a lakehouse, what does each of the bronze, silver and gold layers promise, and where does compaction fit?",
    "medallion"),
];
